version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: surbana_assignment
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DB=postgres
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: npm run start:dev
    networks:
      - surbana

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - surbana

networks:
  surbana:
